[build]
  publish = "dist"
  command = "npm run build"

[build.environment]
  NODE_VERSION = "18"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[context.production.environment]
  VUE_APP_API_URL = "https://concert-booking-api.railway.app/api"

[context.deploy-preview.environment]
  VUE_APP_API_URL = "http://localhost:8000/api"
