[build]
builder = "nixpacks"

[deploy]
startCommand = "python manage.py migrate && python manage.py populate_sample_data && python manage.py collectstatic --noinput && gunicorn concertbooking.wsgi:application"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10
